package com.example.demo.config;

import com.example.demo.model.Department;
import com.example.demo.model.Doctor;
import com.example.demo.model.Hospital;
import com.example.demo.repository.DepartmentRepository;
import com.example.demo.repository.DoctorRepository;
import com.example.demo.repository.HospitalRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.boot.CommandLineRunner;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Component;

@Component
public class DataSeeder implements CommandLineRunner {

    private static final Logger log = LoggerFactory.getLogger(DataSeeder.class);

    private final HospitalRepository hospitalRepository;
    private final DepartmentRepository departmentRepository;
    private final DoctorRepository doctorRepository;
    private final BCryptPasswordEncoder passwordEncoder;

    public DataSeeder(HospitalRepository hospitalRepository,
                      DepartmentRepository departmentRepository,
                      DoctorRepository doctorRepository) {
        this.hospitalRepository = hospitalRepository;
        this.departmentRepository = departmentRepository;
        this.doctorRepository = doctorRepository;
        this.passwordEncoder = new BCryptPasswordEncoder();
    }

    @Override
    public void run(String... args) {
        // Only seed if no data exists yet
        if (hospitalRepository.count() > 0) {
            log.info("Data already seeded — skipping");
            return;
        }

        log.info("Seeding initial data...");

        // --- HOSPITALS ---
        Hospital korleBu = hospitalRepository.save(
                new Hospital("Korle Bu Teaching Hospital",
                        "Guggisberg Ave, Accra", "+233 302 665 901",
                        "info@korlebu.gov.gh", "https://korlebu.gov.gh")
        );

        Hospital ridge = hospitalRepository.save(
                new Hospital("Ridge Hospital",
                        "Castle Rd, Accra", "+233 302 220 000",
                        "info@ridgehospital.gh", null)
        );

        // --- DEPARTMENTS ---
        Department cardio = departmentRepository.save(
                new Department("Cardiology", "CARDIO",
                        "Heart and cardiovascular system diagnosis & treatment",
                        new java.math.BigDecimal("350.00"), korleBu)
        );

        Department ortho = departmentRepository.save(
                new Department("Orthopedics", "ORTHO",
                        "Musculoskeletal system, bones, joints & spine",
                        new java.math.BigDecimal("400.00"), korleBu)
        );

        Department peds = departmentRepository.save(
                new Department("Pediatrics", "PEDS",
                        "Medical care for infants, children & adolescents",
                        new java.math.BigDecimal("250.00"), ridge)
        );

        Department neuro = departmentRepository.save(
                new Department("Neurology", "NEURO",
                        "Nervous system disorders & brain health",
                        new java.math.BigDecimal("500.00"), ridge)
        );

        // --- DOCTORS (workspace IDs auto-generated by DoctorAdminService) ---
        String password = passwordEncoder.encode("admin123");

        // Korle Bu - Cardiology
        doctorRepository.save(new Doctor("Yaw", "Appiah", "Interventional Cardiology",
                "yaw.appiah@korlebu.gov.gh", "+233 501 111 001", "GC-2024-001",
                "CARDIO-DOC-001", password, korleBu, cardio));

        doctorRepository.save(new Doctor("Akua", "Mensah", "Cardiac Electrophysiology",
                "akua.mensah@korlebu.gov.gh", "+233 501 111 002", "GC-2024-002",
                "CARDIO-DOC-002", password, korleBu, cardio));

        // Korle Bu - Orthopedics
        doctorRepository.save(new Doctor("Kwame", "Ofori", "Sports Orthopedics",
                "kwame.ofori@korlebu.gov.gh", "+233 501 111 003", "GC-2024-003",
                "ORTHO-DOC-001", password, korleBu, ortho));

        // Ridge - Pediatrics
        doctorRepository.save(new Doctor("Esi", "Quartey", "General Pediatrics",
                "esi.quartey@ridgehospital.gh", "+233 502 222 001", "GC-2024-004",
                "PEDS-DOC-001", password, ridge, peds));

        // Ridge - Neurology
        doctorRepository.save(new Doctor("Nana", "Boateng", "Neurology",
                "nana.boateng@ridgehospital.gh", "+233 502 222 002", "GC-2024-005",
                "NEURO-DOC-001", password, ridge, neuro));

        log.info("✅ Seeded: 2 hospitals, 4 departments, 5 doctors");
        log.info("🔑 Doctor password: admin123");
    }
}