spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/pulse_db
spring.datasource.username=postgres
spring.datasource.password=mM7177214

# Optional but very useful for development:
spring.jpa.hibernate.ddl-auto=update          
spring.jpa.show-sql=true                      
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# JWT Configuration
jwt.secret=pulse-backend-jwt-secret-key-2026-marvinphil-annorbah-ghana-spring-boot
jwt.expiration=86400000  